name: xpatch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter
  - ipython
  - notebook
  - scipy>=1.7.0
  - tqdm
  - pyyaml
  - pytorch::pytorch>=1.12.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip
  - pip:
    - einops>=0.6.0
    - fsspec>=2022.1.0
    - axial-positional-embedding>=0.2.0
    - colt5-attention>=0.10.0
    - local-attention>=1.4.0
    - sktime>=0.20.0 